services:
  videosvc:
    build: .
    image: videosvc:dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app:rw
      - ./media:/app/media
      # Раскомментируйте и укажите путь к вашим данным на хосте
      # - /path/to/your/data:/data:ro
    


